# Default values for schema-registry-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: landoop/kafka-topics-ui
  tag: 0.9.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  annotations: {}
  ## Limit load balancer source ips to list of CIDRs (where available)
  # loadBalancerSourceRanges: []

kafkaRest:
  url: "http://kafka-rest-cp-kafka-rest"
  port: 8082
  proxy: true

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - kafka-topics-ui.moja2.test.mojaloop.live
  tls: []


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}